version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - DATABASE_HOST=postgres_db
      - DATABASE_PORT=5432
      - DATABASE_USER=master
      - DATABASE_PASSWORD=master
      - DATABASE_NAME=master
    ports:
      - '5000:5000'  # Expose backend on localhost:5000
    depends_on:
      - postgres_db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - VITE_API_URL=http://backend:5000/api  # Direct connection to backend API
    ports:
      - '80:80'  # Expose frontend on localhost:80
    depends_on:
      - backend

  postgres_db:
    image: postgres:latest
    environment:
      POSTGRES_USER: # Enter your desired username
      POSTGRES_PASSWORD: # Enter your desired password
      POSTGRES_DB: # Enter your desired database name
    ports:
      - '5432:5432'  # Expose Postgres on localhost:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
